# Generated by Django 4.0.4 on 2022-05-24 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_remove_snack_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
